# Generated by Django 3.1.3 on 2023-03-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20230321_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.CharField(max_length=100)),
                ('docname', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('dat_e', models.CharField(max_length=1000)),
                ('tim_e', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=1000)),
                ('docid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
