# Generated by Django 3.1.3 on 2023-03-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='stz',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
