# Generated by Django 3.1.3 on 2023-03-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_bookings_stz'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='pemail',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
